#!/bin/bash

touch "$1"
chmod "$2" "$1"

exit 0#!/bin/bash

echo "#!/bin/bash" > "$1"
echo "echo \"GNU is not Unix\"" >> "$1"
echo "exit 0" >> "$1"

chmod "$2" "$1"

exit 0 #!/bin/bash

if [ $# -ne 1 ]; then
  echo "usage: $0 arg"
  exit 1
fi

if [ ! -d "$1" -o ! -r "$1" ]; then
  echo "usage: $0 arg (readable directory)"
  exit 1
fi

exit 0
#!/bin/bash

if [ $# -ne 2 ]; then
  echo "usage: $0 arg1 arg2"
  exit 1
fi

if [ ! -d "$1" -o ! -w "$1" ]; then
  echo "usage: $0 arg1 (writable directory) arg2"
  exit 1
fi

cd "$1"
pwd > "$2"

exit 0
