# Generated by Django 2.1.4 on 2019-01-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
        migrations.AlterModelOptions(
            name='groupmatch',
            options={'verbose_name': 'Group match', 'verbose_name_plural': 'Group matches'},
        ),
        migrations.AlterModelOptions(
            name='knockoutmatch',
            options={'verbose_name': 'Knockout match', 'verbose_name_plural': 'Knockout matches'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='coach',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='date_of_birth',
        ),
    ]
