# Generated by Django 2.1.4 on 2019-01-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190101_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='nation',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
