# Generated by Django 2.1.4 on 2019-01-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_footballer_nation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='footballer',
            unique_together=set(),
        ),
    ]
