# Generated by Django 2.1.4 on 2019-01-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190110_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='assist_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assists', to='core.Footballer'),
        ),
    ]
