# Generated by Django 2.1.4 on 2019-01-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190110_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
