# Generated by Django 2.1.4 on 2019-01-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='redcard',
            name='double_yellow',
            field=models.BooleanField(default=False),
        ),
    ]
