# Generated by Django 2.1.4 on 2019-01-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_club_stadium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballer',
            old_name='club_name',
            new_name='club',
        ),
    ]
