# Generated by Django 2.1.4 on 2019-01-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190114_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='second_club',
            new_name='away_club',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='first_club',
            new_name='home_club',
        ),
    ]
