# Generated by Django 2.1.4 on 2019-01-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190114_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitution',
            name='minute',
            field=models.IntegerField(default=0),
        ),
    ]
