# Generated by Django 2.1.4 on 2019-01-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190115_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmatch',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
