# Generated by Django 2.1.4 on 2019-01-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_groupmatch_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmatch',
            old_name='match',
            new_name='referred_match',
        ),
        migrations.AlterUniqueTogether(
            name='groupmatch',
            unique_together={('group', 'referred_match')},
        ),
    ]
