# Generated by Django 2.1.4 on 2019-01-30 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190130_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmatch',
            name='referred_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_match', to='core.Match'),
        ),
    ]
