# Generated by Django 2.1.4 on 2019-01-30 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190130_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmatch',
            name='referred_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_group_match', to='core.Match'),
        ),
        migrations.AlterField(
            model_name='knockoutmatch',
            name='referred_match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_knockout_match', to='core.Match'),
        ),
    ]
